server {
    listen 80;

    client_max_body_size 2048m;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location /dicom-web/ {
        proxy_pass http://orthanc:8042/dicom-web/;
        proxy_set_header Host $host;
    }

    location ^~ /viewer/ {
        proxy_pass http://viewer:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 匹配所有 Viewer 需要的静态资源
    location ~* \.(js|css|json|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://viewer:80;
        proxy_set_header Host $host;
    }
}
