server {
    listen 80;

    # 【修复】允许最大 1000MB 的 DICOM 文件夹上传
    client_max_body_size 1000M;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /dicom-web/ {
        proxy_pass http://orthanc:8042/dicom-web/;
        proxy_set_header Host $host;
    }

    location ^~ /viewer/ {
        proxy_pass http://viewer:80/;
        proxy_set_header Host $host;
    }

    location ~ ^/(static|assets|fonts|locales|config\.js)/ {
        proxy_pass http://viewer:80;
        proxy_set_header Host $host;
    }
}
